### ISSUE TITLE
Question about future of the repo?

### ISSUE THREAD

**Issue by alexunderch** [FLAIROx/cultural-accumulation#1]
Hey, Chris! Great repository, I wanted to play with the code and maybe to try some other experiments inspired of the codebase. Do you plan to leave the code "as it is" or want to make a thing, people can build on top of? neither?

**Comment by luchris429** [comment]
Hey thanks! I think it should kind of serve as both -- ideally this code doesn't change too much, as it should directly replicate the results in the paper.

It would be neat to make it easier to build on top of, but I'm not sure that we'll have time, especially if only a handful of people would find it useful.
